openapi: 3.0.3
info:
  title: DemoProject API Documentation
  version: 1.0.0
paths:
  #################
  # Auth
  #################

  /auth/authenticate:
    $ref: './auth.yaml#/paths/authenticate'
  /auth/refresh:
    $ref: './auth.yaml#/paths/refresh'

  #################
  # Core
  #################

  /movies/filter:
    $ref: './core.yaml#/paths/movies-filter'

  /movie:
    $ref: './core.yaml#/paths/movie-add'

  /movie/{id}:
    $ref: './core.yaml#/paths/movie'

  /actors/filter:
    $ref: './core.yaml#/paths/actors-filter'

  /actor:
    $ref: './core.yaml#/paths/actor-add'

  /actor/{id}:
    $ref: './core.yaml#/paths/actor'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        instance:
          type: string